{% set name = "ctapipe_io_zfits" %}
{% set version = "0.4.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_zfits-{{ version }}.tar.gz
  sha256: f0dafab9da1009032cd5fb2b9e8cb3983c0fb8cb482b4131b914955c9cd2d4b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - protozfits >=2.7.3,<3.dev0
    - ctapipe >=0.28.0

test:
  imports:
    - ctapipe_io_zfits
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: ctapipe io plugin for reading data in zfits file (ACADA Rel 1 DL0, CTAO R1v1)
  home: https://github.com/cta-observatory/ctapipe_io_lst
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
